paths:
    instance info:
        /home/ubuntu/instance_id
    input:
        initial:
            image:
                /home/ubuntu/mount/img/
            annotation:
                /home/ubuntu/mount/cs543_annotations/
        step one:
            positive:
                /home/ubuntu/mount/cs543/out/sq_image_patch/
            negative:
                /home/ubuntu/mount/cs543/out/sq_negatives/
    output:
        figure save dir:
            /home/ubuntu/mount/cs543/figures/
        data prep:
            image:
                positive:
                    /home/ubuntu/mount/cs543/out/image_patch/
                negative:
                    /home/ubuntu/mount/cs543/out/negative_sample/
            annotation:
                positive:
                    /home/ubuntu/mount/cs543/out/annotation/
                negative:
                    /home/ubuntu/mount/cs543/out/negative_sample/
            square image:
                positive:
                    /home/ubuntu/mount/cs543/out/sq_image_patch/
                negative:
                    /home/ubuntu/mount/cs543/out/sq_negatives/
        first feature extraction:
            positive:
                /home/ubuntu/mount/cs543/out/out/training_data/pos/
            negative:
                /home/ubuntu/mount/cs543/out/out/training_data/neg/
