paths:
    base dir:
        /Users/daeyun/class/cs543/
    instance info:
        /Users/daeyun/instance_id
    input:
        initial:
            image:
                img/
            annotation:
                annotations/
        step one:
            positive:
                out/sq_image_patch/
            negative:
                out/sq_negatives/
        training:
            out/training_data/
    output:
        figure save dir:
            figures/
        data prep:
            image:
                positive:
                    out/image_patch/
                negative:
                    out/negative_sample/
            annotation:
                positive:
                    out/annotation/
                negative:
                    out/negative_sample/
            square image:
                positive:
                    out/sq_image_patch/
                negative:
                    out/sq_negatives/
        first feature extraction:
            out/training_data/
